engine:
  type: "in_memory"
network:
  address: ":3223"
  max_connections: 5
  message_size: "1KB"
logging:
  level: "debug"
  output: "console"
wal:
  flushing_batch_size: 2
  flushing_batch_timeout: "1s"
  max_segment_size: "100b"
  data_directory: "tmp"
  compaction: true
replication:
  replica_type: "master"
  master_address: ":3232"
  sync_interval: "5s"